@echo off
chcp 65001 >nul
setlocal enabledelayedexpansion

:: 自动切换到脚本所在目录（解决管理员权限导致的目录问题）
cd /d "E:\MCR\GTY"
echo [INFO] 当前目录: %cd%

:: ================== 配置区域 ==================
set "REMOTE_URL=https://github.com/bii20081Aztec/CSSAHUV"
set "IGNORE_ITEM=不能上传的东西"
set "COMMIT_MSG=Auto commit from script on %date% %time%"
set "BRANCH=main"

:: Git 用户配置
set "GIT_USERNAME=bii20081Aztec"
set "GIT_EMAIL=bii20081@example.com"
:: =============================================

:: 1. 检查并配置 Git 用户信息
echo [INFO] 检查 Git 用户配置...
git config --global user.name >nul 2>nul
if errorlevel 1 (
    echo [WARN] 未检测到 Git 用户名，正在配置...
    git config --global user.name "%GIT_USERNAME%"
    echo [INFO] 已设置用户名: %GIT_USERNAME%
)

git config --global user.email >nul 2>nul
if errorlevel 1 (
    echo [WARN] 未检测到 Git 邮箱，正在配置...
    git config --global user.email "%GIT_EMAIL%"
    echo [INFO] 已设置邮箱: %GIT_EMAIL%
)

:: 2. 如果 .git 不存在，则初始化仓库
if not exist ".git" (
    echo [INFO] 初始化 Git 仓库...
    git init
    if errorlevel 1 (echo [ERROR] Git 初始化失败 & pause & exit /b 1)
)

:: 3. 配置远程仓库地址
echo [INFO] 设置远程仓库地址: %REMOTE_URL%
git remote remove origin 2>nul
git remote add origin %REMOTE_URL%

:: 4. 添加忽略规则
if not exist ".gitignore" (
    echo [INFO] 创建 .gitignore 文件...
    echo # Auto-generated by script > .gitignore
)

findstr /x /c:"%IGNORE_ITEM%" .gitignore >nul 2>nul
if errorlevel 1 (
    echo [INFO] 添加 "%IGNORE_ITEM%" 到 .gitignore
    echo %IGNORE_ITEM% >> .gitignore
)

:: 5. 移除已追踪的忽略项
git ls-files --error-unmatch %IGNORE_ITEM% >nul 2>nul
if not errorlevel 1 (
    echo [WARN] 移除已追踪的忽略项...
    git rm --cached %IGNORE_ITEM% 2>nul
)

:: 6. 添加所有文件
echo [INFO] 添加所有文件...
git add .

:: 7. 检查是否有文件可以提交
git diff --cached --quiet
if errorlevel 1 (
    echo [INFO] 提交更改...
    git commit -m "%COMMIT_MSG%"
    if errorlevel 1 (
        echo [ERROR] 提交失败
        pause
        exit /b 1
    )
) else (
    echo [WARN] 没有检测到任何文件更改
    echo [INFO] 当前目录可能没有文件，或者所有文件都被忽略了
    echo.
    echo 当前目录内容：
    dir /b
    echo.
    pause
    exit /b 0
)

:: 8. 强制覆盖推送
echo [INFO] 强制覆盖推送到远程仓库...
git push -u origin %BRANCH% --force

if errorlevel 1 (
    echo [ERROR] 强制推送失败！
    pause
    exit /b 1
)

echo [SUCCESS] 推送成功！
pause