modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="school"
version="0.1.19.0"
displayName="Chinese-style school as well as home"
displayURL="https://space.bilibili.com/1685065897"
logoFile="logo.png"
credits="By MCreator"
authors="Variapieabe5171 Wanyantu"
description="The original author of the mod is Wanyan Rabbit, and the current author is not the original author, so the mod will be done according to the ideas of the new author Contributors: MCMOD Imposter"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.school]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.school]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration