
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.xbtstudio.school.init;

import net.xbtstudio.school.SchoolMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.event.BuildCreativeModeTabContentsEvent;

import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class SchoolModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, SchoolMod.MODID);
	public static final RegistryObject<CreativeModeTab> LABORATORY = REGISTRY.register("laboratory",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.school.laboratory")).icon(() -> new ItemStack(SchoolModItems.CHIP.get())).displayItems((parameters, tabData) -> {
				tabData.accept(SchoolModBlocks.SCREEN.get().asItem());
				tabData.accept(SchoolModBlocks.PC.get().asItem());
				tabData.accept(SchoolModBlocks.SEEWO.get().asItem());
				tabData.accept(SchoolModBlocks.AC_OUT.get().asItem());
				tabData.accept(SchoolModBlocks.ACINA.get().asItem());
				tabData.accept(SchoolModBlocks.MAIN_UNIT.get().asItem());
				tabData.accept(SchoolModBlocks.SEEWO_BSOD.get().asItem());
				tabData.accept(SchoolModBlocks.SCHOOL_BELL_CONTROLLER.get().asItem());
				tabData.accept(SchoolModBlocks.BALANCE.get().asItem());
				tabData.accept(SchoolModBlocks.FU.get().asItem());
				tabData.accept(SchoolModBlocks.ACIN_B.get().asItem());
				tabData.accept(SchoolModBlocks.AC_BRACKET.get().asItem());
				tabData.accept(SchoolModBlocks.WHITE_BOARD.get().asItem());
				tabData.accept(SchoolModBlocks.PRINTER.get().asItem());
				tabData.accept(SchoolModBlocks.PCMC.get().asItem());
				tabData.accept(SchoolModBlocks.OLD_PC.get().asItem());
				tabData.accept(SchoolModBlocks.OLD_PC_GSLC.get().asItem());
				tabData.accept(SchoolModBlocks.LOUDSPEAKER.get().asItem());
				tabData.accept(SchoolModBlocks.AC_LARGE_OUT.get().asItem());
				tabData.accept(SchoolModBlocks.SPRING_FESTIVAL_COUPLETS.get().asItem());
				tabData.accept(SchoolModBlocks.EASICAMERA.get().asItem());
				tabData.accept(SchoolModBlocks.SMART_BRAND.get().asItem());
				tabData.accept(SchoolModBlocks.LAPTOP.get().asItem());
				tabData.accept(SchoolModBlocks.OUTDOORSPEAKERS.get().asItem());
				tabData.accept(SchoolModBlocks.WINDOWAIRCONDITIONING.get().asItem());
				tabData.accept(SchoolModBlocks.WINDOWAIRCONDITIONERBLACKWINDOW.get().asItem());
				tabData.accept(SchoolModBlocks.WINDOWAIRCONDITIONERBLUEWINDOW.get().asItem());
				tabData.accept(SchoolModBlocks.WINDOWAIRCONDITIONERGREENWINDOW.get().asItem());
				tabData.accept(SchoolModBlocks.NOTV.get().asItem());
				tabData.accept(SchoolModBlocks.SATELLITETELEVISION.get().asItem());
				tabData.accept(SchoolModBlocks.DTMBDVBT.get().asItem());
				tabData.accept(SchoolModBlocks.NOCRTTV.get().asItem());
				tabData.accept(SchoolModBlocks.FM_RADIO.get().asItem());
				tabData.accept(SchoolModBlocks.PCW_7.get().asItem());
				tabData.accept(SchoolModBlocks.SLANTAIRCONDITION.get().asItem());
				tabData.accept(SchoolModBlocks.CIRCULARAIRCONDITIONING.get().asItem());
				tabData.accept(SchoolModBlocks.DESKWITHDESKTOPCOMPUTER.get().asItem());
				tabData.accept(SchoolModBlocks.PCWXP.get().asItem());
				tabData.accept(SchoolModBlocks.PCW_8.get().asItem());
				tabData.accept(SchoolModBlocks.PCW_10.get().asItem());
				tabData.accept(SchoolModBlocks.DVBCABLE.get().asItem());
				tabData.accept(SchoolModBlocks.ACTIVEOPTICALACCESSDEVICES.get().asItem());
				tabData.accept(SchoolModItems.US_BDRIVE.get());
				tabData.accept(SchoolModBlocks.BROADCASTCREW.get().asItem());
				tabData.accept(SchoolModBlocks.PCDELK.get().asItem());
				tabData.accept(SchoolModBlocks.DVBTS.get().asItem());
				tabData.accept(SchoolModBlocks.UBUNTU_SEEWO.get().asItem());
				tabData.accept(SchoolModBlocks.OFFS_NETWORK.get().asItem());
				tabData.accept(SchoolModBlocks.WATERDISPENSER.get().asItem());
				tabData.accept(SchoolModBlocks.LIGHTCATSETTOPBOX.get().asItem());
			}).build());
	public static final RegistryObject<CreativeModeTab> SCHOOL = REGISTRY.register("school",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.school.school")).icon(() -> new ItemStack(Blocks.BELL)).displayItems((parameters, tabData) -> {
				tabData.accept(SchoolModItems.FERULE.get());
				tabData.accept(SchoolModItems.SET_SQUARE.get());
				tabData.accept(SchoolModBlocks.BLACK_BOARD.get().asItem());
				tabData.accept(SchoolModBlocks.DESK.get().asItem());
				tabData.accept(SchoolModBlocks.CHAIR.get().asItem());
				tabData.accept(SchoolModBlocks.BOOKS.get().asItem());
				tabData.accept(SchoolModBlocks.LABORATORY_DESK.get().asItem());
				tabData.accept(SchoolModBlocks.LABORATORY_POOL.get().asItem());
				tabData.accept(SchoolModBlocks.LABORATORY_CHAIR.get().asItem());
				tabData.accept(SchoolModBlocks.ALCOHOL_LAMP.get().asItem());
				tabData.accept(SchoolModBlocks.LABORATORY_CABINET.get().asItem());
				tabData.accept(SchoolModBlocks.LABORATORY_LIGHT.get().asItem());
				tabData.accept(SchoolModItems.CHALK.get());
				tabData.accept(SchoolModBlocks.PROJECTOR.get().asItem());
				tabData.accept(SchoolModItems.CHALKS.get());
				tabData.accept(SchoolModItems.LABORATORY_SUGAR.get());
				tabData.accept(SchoolModItems.COLORFUL_INK_BAGS.get());
				tabData.accept(SchoolModItems.STUDENT_MILK.get());
				tabData.accept(SchoolModItems.STUDENT_MEAL.get());
				tabData.accept(SchoolModItems.PIECE_OF_TEST_BOOK.get());
				tabData.accept(SchoolModBlocks.CERTIFICATE_OF_MERIT.get().asItem());
				tabData.accept(SchoolModItems.CHALK_HAIR_SPRAYER.get());
				tabData.accept(SchoolModItems.CHALK_SMG.get());
				tabData.accept(SchoolModItems.CHALK_RF.get());
				tabData.accept(SchoolModItems.CHALK_CANNON.get());
				tabData.accept(SchoolModBlocks.CLASSCARD.get().asItem());
				tabData.accept(SchoolModBlocks.PUSHANDPULLCHALKBOARD_1.get().asItem());
				tabData.accept(SchoolModBlocks.PUSHANDPULLCHALKBOARD_2.get().asItem());
				tabData.accept(SchoolModBlocks.PUSHANDPULLCHALKBOARD_3.get().asItem());
				tabData.accept(SchoolModBlocks.PUSHANDPULLCHALKBOARD_4.get().asItem());
				tabData.accept(SchoolModBlocks.MOBILE_RED_FLAGS.get().asItem());
				tabData.accept(SchoolModBlocks.MOBILEBLACK.get().asItem());
				tabData.accept(SchoolModBlocks.STUDYHARD.get().asItem());
				tabData.accept(SchoolModBlocks.EVERYDAY.get().asItem());
				tabData.accept(SchoolModBlocks.PODIUM.get().asItem());
				tabData.accept(SchoolModBlocks.BLUEMUSICCHAIR.get().asItem());
				tabData.accept(SchoolModBlocks.ORANGEMUSICCHAIR.get().asItem());
				tabData.accept(SchoolModBlocks.GREENMUSICCHAIR.get().asItem());
				tabData.accept(SchoolModBlocks.YELLOWMUSICCHAIR.get().asItem());
				tabData.accept(SchoolModBlocks.REDMUSICCHAIR.get().asItem());
				tabData.accept(SchoolModBlocks.VISUALACUITYCHART.get().asItem());
				tabData.accept(SchoolModBlocks.CODEFORSTUDENTS.get().asItem());
				tabData.accept(SchoolModBlocks.BILLBOARDS.get().asItem());
				tabData.accept(SchoolModBlocks.LABORATORYEXHAUSTHOOD.get().asItem());
				tabData.accept(SchoolModBlocks.LABORATORYEXHAUSTHOOD_2_X_2.get().asItem());
				tabData.accept(SchoolModBlocks.CLASSCARD_2.get().asItem());
				tabData.accept(SchoolModBlocks.CLASSCARD_3.get().asItem());
			}).withTabsBefore(LABORATORY.getId()).build());
	public static final RegistryObject<CreativeModeTab> WINDOWSCANBEOPENED = REGISTRY.register("windowscanbeopened",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.school.windowscanbeopened")).icon(() -> new ItemStack(SchoolModBlocks.SMALLSLIDINGWINDOW.get())).displayItems((parameters, tabData) -> {
				tabData.accept(SchoolModBlocks.WINDOW_BLACK_UP.get().asItem());
				tabData.accept(SchoolModBlocks.WINDOW_BLACK_DOWN.get().asItem());
				tabData.accept(SchoolModBlocks.WINDOW_WHITE_DOWN.get().asItem());
				tabData.accept(SchoolModBlocks.WINDOW_WHITE_UP.get().asItem());
				tabData.accept(SchoolModBlocks.WINDOW_BLACK_DOWN_SINGLE.get().asItem());
				tabData.accept(SchoolModBlocks.WINDOW_BLACK_UP_SINGLE.get().asItem());
				tabData.accept(SchoolModBlocks.WINDOW_WHITE_UP_SINGLE.get().asItem());
				tabData.accept(SchoolModBlocks.WINDOW_WHITE_DOWN_SINGLE.get().asItem());
				tabData.accept(SchoolModBlocks.WINDOW_OLD_DOWN.get().asItem());
				tabData.accept(SchoolModBlocks.WINDOW_OLD_UP.get().asItem());
				tabData.accept(SchoolModBlocks.WINDOW_OLD_DOWN_SINGLE.get().asItem());
				tabData.accept(SchoolModBlocks.WINDOW_OLD_UP_SINGLE.get().asItem());
				tabData.accept(SchoolModBlocks.GREENDOUBLEGLASSWINDOWS.get().asItem());
				tabData.accept(SchoolModBlocks.MINIGREENVINTAGEGLASSWINDOWS.get().asItem());
				tabData.accept(SchoolModBlocks.MINIGREENVINTAGEGLASSWINDOWS_1.get().asItem());
				tabData.accept(SchoolModBlocks.GREENVINTAGEGLASSWINDOWS_1.get().asItem());
				tabData.accept(SchoolModBlocks.SMALLWINDOWS_1.get().asItem());
				tabData.accept(SchoolModBlocks.SMALLWINDOWSWHITE.get().asItem());
				tabData.accept(SchoolModBlocks.SMALLWINDOWSBLACK.get().asItem());
				tabData.accept(SchoolModBlocks.SMALLWINDOWSBLACK_1.get().asItem());
				tabData.accept(SchoolModBlocks.SMALLWINDOWSBLUE.get().asItem());
				tabData.accept(SchoolModBlocks.SMALLWINDOWSBLUE_1.get().asItem());
				tabData.accept(SchoolModBlocks.SMALLWINDOWSGREEN.get().asItem());
				tabData.accept(SchoolModBlocks.SMALLWINDOWSGREEN_1.get().asItem());
				tabData.accept(SchoolModBlocks.CORNERWINDOWS.get().asItem());
				tabData.accept(SchoolModBlocks.CORNERWINDOWS_1.get().asItem());
				tabData.accept(SchoolModBlocks.CORNERWINDOWS_2.get().asItem());
				tabData.accept(SchoolModBlocks.CORNERWINDOWS_3.get().asItem());
				tabData.accept(SchoolModBlocks.CORNERWINDOWS_HENGSU.get().asItem());
				tabData.accept(SchoolModBlocks.CORNERWINDOWS_HENGSU_1.get().asItem());
				tabData.accept(SchoolModBlocks.CORNERWINDOWS_HENGSU_3.get().asItem());
				tabData.accept(SchoolModBlocks.CORNERWINDOWS_HENGSU_4.get().asItem());
				tabData.accept(SchoolModBlocks.CORNERWINDOWSSMALL.get().asItem());
				tabData.accept(SchoolModBlocks.CORNERWINDOWSSMALL_1.get().asItem());
				tabData.accept(SchoolModBlocks.CORNERWINDOWSSMALL_2.get().asItem());
				tabData.accept(SchoolModBlocks.CORNERWINDOWSSMALL_3.get().asItem());
				tabData.accept(SchoolModBlocks.SLIDINGWINDOWS.get().asItem());
				tabData.accept(SchoolModBlocks.SLIDINGWINDOWS_BLACK.get().asItem());
				tabData.accept(SchoolModBlocks.SLIDINGWINDOWS_BLUE.get().asItem());
				tabData.accept(SchoolModBlocks.SLIDINGWINDOWS_GREEN.get().asItem());
				tabData.accept(SchoolModBlocks.SMALLSLIDINGWINDOW.get().asItem());
				tabData.accept(SchoolModBlocks.SMALLSLIDINGWINDOW_BLACK.get().asItem());
				tabData.accept(SchoolModBlocks.SMALLSLIDINGWINDOW_BLUE.get().asItem());
				tabData.accept(SchoolModBlocks.SMALLSLIDINGWINDOW_GREEN.get().asItem());
				tabData.accept(SchoolModBlocks.EXTRALARGESLIDINGWINDOWS.get().asItem());
				tabData.accept(SchoolModBlocks.EXTRALARGESLIDINGWINDOWS_BLACK.get().asItem());
				tabData.accept(SchoolModBlocks.EXTRALARGESLIDINGWINDOWS_BLUE.get().asItem());
				tabData.accept(SchoolModBlocks.EXTRALARGESLIDINGWINDOWS_GREEN.get().asItem());
				tabData.accept(SchoolModBlocks.LARGESLIDINGWINDOWS.get().asItem());
				tabData.accept(SchoolModBlocks.LARGESLIDINGWINDOWS_BLACK.get().asItem());
				tabData.accept(SchoolModBlocks.LARGESLIDINGWINDOWS_BLUE.get().asItem());
				tabData.accept(SchoolModBlocks.LARGESLIDINGWINDOWS_GREEN.get().asItem());
				tabData.accept(SchoolModBlocks.MINISLIDINGWINDOW.get().asItem());
				tabData.accept(SchoolModBlocks.MINISLIDINGWINDOW_BLACK.get().asItem());
				tabData.accept(SchoolModBlocks.MINISLIDINGWINDOW_BLUE.get().asItem());
				tabData.accept(SchoolModBlocks.MINISLIDINGWINDOW_GREEN.get().asItem());
				tabData.accept(SchoolModBlocks.ONTHEMINISLIDINGWINDOW.get().asItem());
				tabData.accept(SchoolModBlocks.ONTHEMINISLIDINGWINDOW_BLACK.get().asItem());
				tabData.accept(SchoolModBlocks.ONTHEMINISLIDINGWINDOW_BLUE.get().asItem());
				tabData.accept(SchoolModBlocks.ONTHEMINISLIDINGWINDOW_GREEN.get().asItem());
				tabData.accept(SchoolModBlocks.LARGEGLASSWINDOW.get().asItem());
				tabData.accept(SchoolModBlocks.UPPERWIDEGLASSWINDOWS_BLACK.get().asItem());
				tabData.accept(SchoolModBlocks.UPPERWIDEGLASSWINDOWS_GREEN.get().asItem());
				tabData.accept(SchoolModBlocks.UPPERWIDEGLASSWINDOWS_GREENA.get().asItem());
				tabData.accept(SchoolModBlocks.LARGEGLASSWINDOW_Q.get().asItem());
				tabData.accept(SchoolModBlocks.LARGEGLASSWINDOWS_BLACK.get().asItem());
				tabData.accept(SchoolModBlocks.LARGEGLASSWINDOWS_BLUE.get().asItem());
				tabData.accept(SchoolModBlocks.LARGEGLASSWINDOW_GREEN.get().asItem());
				tabData.accept(SchoolModBlocks.LARGEGLASSSLIDINGWINDOWS.get().asItem());
				tabData.accept(SchoolModBlocks.LARGEGLASSSLIDINGWINDOWSBLACK.get().asItem());
				tabData.accept(SchoolModBlocks.LARGEGLASSSLIDINGWINDOWSBLUE.get().asItem());
				tabData.accept(SchoolModBlocks.LARGEGLASSSLIDINGWINDOWSGREEN.get().asItem());
				tabData.accept(SchoolModBlocks.CASEMENTWINDOWS_1X_2.get().asItem());
				tabData.accept(SchoolModBlocks.CASEMENTWINDOWS_1X_12.get().asItem());
				tabData.accept(SchoolModBlocks.CASEMENTWINDOWS.get().asItem());
				tabData.accept(SchoolModBlocks.CAASEMENTWINDOWS_1X_2.get().asItem());
				tabData.accept(SchoolModBlocks.CASEMENTWINDOWS_1X_21.get().asItem());
				tabData.accept(SchoolModBlocks.CASEMENTWINDOWS_11.get().asItem());
				tabData.accept(SchoolModBlocks.ANTITHEFTNETS_2X_2.get().asItem());
				tabData.accept(SchoolModBlocks.ANTITHEFTNETS_2_X_1.get().asItem());
				tabData.accept(SchoolModBlocks.ANTITHEFTNETS_1_X_2.get().asItem());
				tabData.accept(SchoolModBlocks.ANTITHEFTNETS_1_X_1.get().asItem());
				tabData.accept(SchoolModBlocks.ANTITHEFTNETS_AIR.get().asItem());
				tabData.accept(SchoolModBlocks.UPPERWIDEGLASSWINDOWSBLAC_K_1.get().asItem());
				tabData.accept(SchoolModBlocks.UPPERWIDEGLASSWINDOWSBL_UE.get().asItem());
				tabData.accept(SchoolModBlocks.UPPERWIDEGLASSWINDOWS_GE.get().asItem());
				tabData.accept(SchoolModBlocks.UPPERWIDEGLASSWINDOWS_WH.get().asItem());
				tabData.accept(SchoolModBlocks.SMALLSLIDINGWINDO.get().asItem());
				tabData.accept(SchoolModBlocks.SMALLSLIDINGWINDOBBK.get().asItem());
				tabData.accept(SchoolModBlocks.LARGESLIDINGWINDOW.get().asItem());
				tabData.accept(SchoolModBlocks.LARGESLIDINGWINDOBBK.get().asItem());
				tabData.accept(SchoolModBlocks.SMALLSLIDINWINDOWBLUE.get().asItem());
				tabData.accept(SchoolModBlocks.LARGESLIDINGWINDOWS_BL.get().asItem());
				tabData.accept(SchoolModBlocks.SMALLSLIDINGWINDOWGREE.get().asItem());
				tabData.accept(SchoolModBlocks.LARGESLIDINGWINDOWS_GE.get().asItem());
			}).withTabsBefore(SCHOOL.getId()).build());
	public static final RegistryObject<CreativeModeTab> BUILD = REGISTRY.register("build",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.school.build")).icon(() -> new ItemStack(Items.DIAMOND_PICKAXE)).displayItems((parameters, tabData) -> {
				tabData.accept(SchoolModBlocks.CLASSROOM_LIGHT.get().asItem());
				tabData.accept(SchoolModBlocks.GLASS_FLOOR.get().asItem());
				tabData.accept(SchoolModBlocks.GLASS_DOOR.get().asItem());
				tabData.accept(SchoolModBlocks.TALL_WALL.get().asItem());
				tabData.accept(SchoolModBlocks.WHITE_CONCRETE_STAIR.get().asItem());
				tabData.accept(SchoolModBlocks.WHITE_CONCRETE_WALL.get().asItem());
				tabData.accept(SchoolModBlocks.TOP_LAMP.get().asItem());
				tabData.accept(SchoolModBlocks.STRIP_CHANDELIER.get().asItem());
				tabData.accept(SchoolModBlocks.TALL_WALL_CORNER.get().asItem());
				tabData.accept(SchoolModBlocks.RADIATOR.get().asItem());
				tabData.accept(SchoolModBlocks.CLASSROOMDOORS.get().asItem());
				tabData.accept(SchoolModBlocks.TABLETENNISTABLE.get().asItem());
				tabData.accept(SchoolModBlocks.ITMUSTHAVEBEEN_OPTIFINETODOIT.get().asItem());
				tabData.accept(SchoolModBlocks.OUTDOORSLIDINGDOORS.get().asItem());
				tabData.accept(SchoolModBlocks.OUTDOORSLIDINGDOORS_1.get().asItem());
				tabData.accept(SchoolModBlocks.TILE.get().asItem());
				tabData.accept(SchoolModBlocks.BLACKTILES.get().asItem());
				tabData.accept(SchoolModBlocks.LARGETILES.get().asItem());
				tabData.accept(SchoolModBlocks.OUTDOORTILES.get().asItem());
				tabData.accept(SchoolModBlocks.MARBLETILES.get().asItem());
				tabData.accept(SchoolModBlocks.HIGHSPEEDRAILRAILINGS.get().asItem());
				tabData.accept(SchoolModBlocks.IRONBARS.get().asItem());
				tabData.accept(SchoolModBlocks.SCHOOLTABLES.get().asItem());
				tabData.accept(SchoolModBlocks.SQUATTINGURINAL.get().asItem());
				tabData.accept(SchoolModBlocks.CANTEENINSULATEDTABLE.get().asItem());
				tabData.accept(SchoolModBlocks.CANTEENKITCHENCOUNTERTOP.get().asItem());
				tabData.accept(SchoolModBlocks.CAFETERIAKITCHENSINK.get().asItem());
				tabData.accept(SchoolModBlocks.CANTEENKITCHENSTOVE.get().asItem());
				tabData.accept(SchoolModBlocks.CANTEENKITCHENREFRIGERATOR.get().asItem());
				tabData.accept(SchoolModBlocks.REDCONCRETEWALL.get().asItem());
				tabData.accept(SchoolModBlocks.RE_DCONCRETESTAIR.get().asItem());
				tabData.accept(SchoolModBlocks.GREENCONCRETEWALL.get().asItem());
				tabData.accept(SchoolModBlocks.GREENCONCRETESTAIR.get().asItem());
				tabData.accept(SchoolModBlocks.BLUECONCRETEWALL.get().asItem());
				tabData.accept(SchoolModBlocks.BLUECONCRETESTAIRQ.get().asItem());
				tabData.accept(SchoolModBlocks.ORANGECONCRETESTAIR.get().asItem());
				tabData.accept(SchoolModBlocks.ORANGECONCRETESTAIR_Q.get().asItem());
				tabData.accept(SchoolModBlocks.YELLOWCONCRETEWALL.get().asItem());
				tabData.accept(SchoolModBlocks.YELLOWCONCRETESTAIR.get().asItem());
				tabData.accept(SchoolModBlocks.BLACKCONCRETEWALL.get().asItem());
				tabData.accept(SchoolModBlocks.BLACKCONCRETESTAIR.get().asItem());
				tabData.accept(SchoolModBlocks.GREYCONCRETEWALL.get().asItem());
				tabData.accept(SchoolModBlocks.GREYCONCRETESTAIR.get().asItem());
				tabData.accept(SchoolModBlocks.REDTALLWALL.get().asItem());
				tabData.accept(SchoolModBlocks.GREENTALLWALL.get().asItem());
				tabData.accept(SchoolModBlocks.BLUETALLWALL.get().asItem());
				tabData.accept(SchoolModBlocks.ORANGETALLWALL.get().asItem());
				tabData.accept(SchoolModBlocks.YELLOWTALLWALL.get().asItem());
				tabData.accept(SchoolModBlocks.BLACKTALLWALL.get().asItem());
				tabData.accept(SchoolModBlocks.GREYTALLWALL.get().asItem());
				tabData.accept(SchoolModBlocks.RE_DTALLWALLCORNER.get().asItem());
				tabData.accept(SchoolModBlocks.GREENTALLWALLCORNER.get().asItem());
				tabData.accept(SchoolModBlocks.BLUETALLWALLCORNER.get().asItem());
				tabData.accept(SchoolModBlocks.ORANGETALLWALLCORNER.get().asItem());
				tabData.accept(SchoolModBlocks.YELLOWTALLWALLCORNER.get().asItem());
				tabData.accept(SchoolModBlocks.BLACKTALLWALLCORNER.get().asItem());
				tabData.accept(SchoolModBlocks.GREYTALLWALLCORNER.get().asItem());
				tabData.accept(SchoolModBlocks.FITNESSTREADMILL.get().asItem());
				tabData.accept(SchoolModBlocks.TANDEMPEDALTRAINER.get().asItem());
				tabData.accept(SchoolModBlocks.ROCKERBOARDFORCHILDREN.get().asItem());
				tabData.accept(SchoolModBlocks.SPACEWALKER.get().asItem());
				tabData.accept(SchoolModBlocks.TOILETDOORPANELS.get().asItem());
				tabData.accept(SchoolModBlocks.TOILETDOORPANELS_MI.get().asItem());
				tabData.accept(SchoolModBlocks.TOILETDOORS.get().asItem());
				tabData.accept(SchoolModBlocks.TOILETDOORS_MI.get().asItem());
				tabData.accept(SchoolModBlocks.PIPE.get().asItem());
				tabData.accept(SchoolModBlocks.PIPEB.get().asItem());
				tabData.accept(SchoolModBlocks.PIPEC.get().asItem());
				tabData.accept(SchoolModBlocks.PIPED.get().asItem());
				tabData.accept(SchoolModBlocks.PIPEE.get().asItem());
				tabData.accept(SchoolModBlocks.HALFWALLFENCE.get().asItem());
				tabData.accept(SchoolModBlocks.TERRAZZO.get().asItem());
				tabData.accept(SchoolModBlocks.PIPEG.get().asItem());
				tabData.accept(SchoolModBlocks.PIPEH.get().asItem());
				tabData.accept(SchoolModBlocks.PIPEF.get().asItem());
				tabData.accept(SchoolModBlocks.PIPEI.get().asItem());
				tabData.accept(SchoolModBlocks.CORPORATDESK.get().asItem());
				tabData.accept(SchoolModBlocks.PIPEJ.get().asItem());
				tabData.accept(SchoolModBlocks.FLUORESCENTLAMPS.get().asItem());
				tabData.accept(SchoolModBlocks.RECALSOOM.get().asItem());
				tabData.accept(SchoolModBlocks.RESTAURANTEXHAUSTHOOD.get().asItem());
			}).withTabsBefore(WINDOWSCANBEOPENED.getId()).build());

	@SubscribeEvent
	public static void buildTabContentsVanilla(BuildCreativeModeTabContentsEvent tabData) {
		if (tabData.getTabKey() == CreativeModeTabs.INGREDIENTS) {
			tabData.accept(SchoolModItems.CHIP.get());
		}
	}
}
